/**
 * Mock Property Data
 * 
 * This file contains the data structure for properties with images.
 * You can use this to map over in your React components or to seed your database.
 */
export const properties = [
    {
        title: "Modern Luxury Villa", 
        slug: "modern-luxury-villa-beverly-hills",
        description: "Experience the epitome of luxury living in this stunning modern villa. Featuring floor-to-ceiling windows, a private infinity pool, and smart home integration throughout.",
        price: 2500000.00,
        type: "Villa",
        status: "For Sale",
        bedrooms: 5,
        bathrooms: 4,
        area: 4200, // sqft
        address: "123 Palm Avenue",
        city: "Beverly Hills",
        state: "CA",
        zipcode: "90210",
        image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        is_featured: true,
        views: 1250,
    },
    {
        title: "Contemporary Urban Apartment",
        slug: "contemporary-urban-apartment-ny",
        description: "A sleek and stylish apartment in the heart of the city. Perfect for professionals, offering easy access to business districts and vibrant nightlife.",
        price: 850000.00,
        type: "Apartment",
        status: "For Sale",
        bedrooms: 2,
        bathrooms: 2,
        area: 1100,
        address: "45 Skyline Dr, Apt 12B",
        city: "New York",
        state: "NY",
        zipcode: "10001",
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        is_featured: false,
        views: 840,
    },
    {
        title: "Cozy Suburban Family Home",
        slug: "cozy-suburban-family-home",
        description: "Charm and comfort combine in this lovely family home. Features a spacious backyard, renovated kitchen, and a friendly neighborhood atmosphere.",
        price: 550000.00,
        type: "House",
        status: "Pending",
        bedrooms: 3,
        bathrooms: 2,
        area: 1800,
        address: "78 Maple Street",
        city: "Austin",
        state: "TX",
        zipcode: "78701",
        image: "https://images.unsplash.com/photo-1568605114967-8130f3a36f89?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        is_featured: true,
        views: 2100,
    },
    {
        title: "Spacious Commercial Office",
        slug: "spacious-commercial-office-downtown",
        description: "Prime commercial space located in the business hub. Open floor plan, ready for customization, with excellent natural light and accessibility.",
        price: 1200000.00,
        type: "Commercial",
        status: "For Rent",
        bedrooms: 0,
        bathrooms: 2,
        area: 3000,
        address: "101 Commerce Blvd",
        city: "Chicago",
        state: "IL",
        zipcode: "60601",
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        is_featured: false,
        views: 450,
    },
    {
        title: "Minimalist Seaside Condo",
        slug: "minimalist-seaside-condo-miami",
        description: "Wake up to ocean views in this stunning minimalist condo. Amenities include a gym, pool access, and private beach entry.",
        price: 950000.00,
        type: "Condo",
        status: "For Sale",
        bedrooms: 2,
        bathrooms: 2,
        area: 1350,
        address: "500 Ocean Drive",
        city: "Miami",
        state: "FL",
        zipcode: "33139",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        is_featured: true,
        views: 3200,
    },
    {
        title: "Rustic Country Estate",
        slug: "rustic-country-estate-nashville",
        description: "Escape to the country in this expansive estate. Large plot of land, historic architecture, and peaceful surroundings.",
        price: 1800000.00,
        type: "Land",
        status: "For Sale",
        bedrooms: 6,
        bathrooms: 5,
        area: 5500,
        address: "88 Country Road",
        city: "Nashville",
        state: "TN",
        zipcode: "37201",
        image: "https://images.unsplash.com/photo-1600596542815-2495db9dc2c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        is_featured: false,
        views: 600,
    }
];
